### ISSUE TITLE
Big Sur support with Clover

### ISSUE THREAD

**Issue by Lusanta25** [SkyrilHD/Dell-E7250-Hackintosh#13]
Hey @SkyrilHD, I need a piece of advice: have you tested Big Sur on this laptop with clover ? 
Thanks in advance, cheers. 
Luca

**Comment by SkyrilHD** [comment]
@Lusanta25 Hi,

you might want check my 11.0 branch: https://github.com/SkyrilHD/Dell-E7250-Hackintosh/tree/11.0

After Big Sur release, the current Catalina config will be replaced by this one.

About Clover: I dropped support since as I stated in the README I have little to no time to support 2 bootloaders which takes a lot of time to debug.

Since I dropped Clover support, I had the opportunity to take the time I would investigate on Clover to fix F11 and F12 brightness keys...

**Comment by Lusanta25** [comment]
The problem is that I haven't ever tried Open Core and I don't even now how to start ;((((

**Comment by SkyrilHD** [comment]
You just have to copy the EFI folder :)

You can use an external stick to try out OpenCore.

**Comment by Lusanta25** [comment]
Really is that easy?... So If I've understood well, I just need to: 
1. install opencore on an external pen
2. copy the efi in the USB in the right folder
3. try out opencore selecting from the BIOS the USB pen 
Is it right ? 
Thanks in advance for your advice, cheers. 
Luca

**Comment by SkyrilHD** [comment]
@Lusanta25 Yes.

Make sure the USB is formatted as FAT32 and copy the EFI folder like you would install Clover.

If you like OpenCore, mount your EFI partition of the current system, delete the old EFI and replace it with the current one

**Comment by Lusanta25** [comment]
@SkyrilHD Thanks for the explanation, I have one more doubt: what do you mean by "copy the EFI folder like you would install Clover" ? 
Thanks in advance, cheers.
Luca

**Comment by SkyrilHD** [comment]
@Lusanta25 I mean, you know how to install the Clover EFI? If yes, it is the same.

**Comment by Lusanta25** [comment]
yes, kind of, I usually do this process: 
1. install clover from a dmg directly on the USB
2. after mount the EFI with Clover Configurator 
3. Replace the standard EFI with the one I want to put simply using the finder 
4. That's it 
Is it right ?

**Comment by SkyrilHD** [comment]
@Lusanta25 the first step is unnecessary since my Clover includes Clover itself.

How to install the OpenCore EFI to make it bootable without an USB:

1. Mount your EFI partition with e.g. Clover Configurator but I recommend using MountEFI
2. Open the partition
3. Delete the old EFI
4. Copy the new one over

**Comment by Lusanta25** [comment]
And simply after copying this EFI folder on my dell that is now working with Clover on Catalina can I simply boot with OpenCore ?

**Comment by SkyrilHD** [comment]
@Lusanta25 Yes, but you need to remove the Clover EFI, obviously.

**Comment by Lusanta25** [comment]
Yes, so I can do it directly on the SSD and not on the USB, right ?

**Comment by SkyrilHD** [comment]
@Lusanta25 Yes.

**Comment by Lusanta25** [comment]
okay, I'll give it a go :)))

**Comment by Lusanta25** [comment]
Yeahhhhh, it worked perfectly, thanks mate, you are the best !

**Comment by Lusanta25** [comment]
@SkyrilHD Today should be the day when I can directly update my dell with Catalina to Big Sur with the apple tool ? 
Do you have any advice for me ?

**Comment by SkyrilHD** [comment]
To be honest, I would just wait until Big Sur gets released on the App Store and upgrade with the app

**Comment by Lusanta25** [comment]
when do you think it will be released on the App Store ?

**Comment by SkyrilHD** [comment]
I don't know... Maybe in 3-4 hours

**Comment by Lusanta25** [comment]
Okay, and after when it is released is super simple to update, isn't it ? Maybe the only thing I have to do Is to press when it will reboot in the open core GUI the voice "Boot Mac OS from Update Mac OS ... " ?

**Comment by SkyrilHD** [comment]
Yes, if you use my 11.0 OpenCore EFI, you shouldn't face any problems... I clean installed a beta version of Big Sur without a problem

**Comment by Lusanta25** [comment]
Perfect, I'll let you know.

**Comment by SkyrilHD** [comment]
I will close this issue since Big Sur got released
