### ISSUE TITLE
Ethernet Problem

### ISSUE THREAD

**Issue by Lusanta25** [SkyrilHD/Dell-E7250-Hackintosh#14]
Hey @SkyrilHD, sorry If I disturb you once again, you know that I've recently passed to open core but I've found a little bit of a problem: simply the ethernet doesn't wanna work. 
Do you have any ideas on how to fix this matter ? 
PS: I will attach a video where you can see the lights popping in the back but the ethernet still don't wanna work. 
https://drive.google.com/file/d/1uERDHfKIIDe_N251Emol46X8AN6dFL3j/view?usp=sharing

**Comment by SkyrilHD** [comment]
Hi,

your video needs permission to watch, so remove the permission.

Can you export an IORegistry, so I can look further into the issue?
https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-302.zip

But as far as I can tell, I have no issues with Ethernet and I am connected to the internet.

![image](https://user-images.githubusercontent.com/28839925/98834132-23f91c80-243f-11eb-976e-3d941156aba1.png)

**Comment by Lusanta25** [comment]
Okay, I've removed the block with the permission, so now you should be able to see it. As far as the IoRegistry file is concerned I've attached it down here. 
Cheers, Luca.
[MacBook Pro di Luca.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/5525193/MacBook.Pro.di.Luca.zip)

**Comment by SkyrilHD** [comment]
Looking at your IORegistry, I don't see anything wrong with it. But I noticed you are running an older version of the kext. It seems like you are using the 10.15 OpenCore... Try with the latest one: https://github.com/SkyrilHD/Dell-E7250-Hackintosh/tree/11.0

This has an updated version of the kext.

**Comment by Lusanta25** [comment]
Okay, I'll try it later this night and let you know something :))))

**Comment by SkyrilHD** [comment]
@Lusanta25 Disclaimer: You might want to try this EFI with an external USB due to SecureBootModel...

https://dortania.github.io/OpenCore-Post-Install/universal/security/applesecureboot.html#securebootmodel

Follow the troubleshooting guide, which is under SecureBootModel... If you can't see the troubleshooting guide, scroll down until you see ApECID as title and above there should be the troubleshooting guide.

**Comment by Lusanta25** [comment]
Hey @SkyrilHD I've tried to understand the guide you linked me but at the moment is too much complicated for my noobness :((((

**Comment by SkyrilHD** [comment]
Well, I will try explaining the steps:

- open Terminal
- type `diskutil list`
- look for "Preboot" and on the right side remember the Identifier which would be diskXsY (X and Y are numbers)
- type `diskutil mount diskXsY` while replacing X and Y with the right identifier
- after that go to your "Preboot" partition by typing this command: `cd /System/Volumes/Preboot`
- type `ls`... you should see a long text with numbers and letters (if you have multiple lines of it, tell me)
- type `cd ~`
- copy the long text and type (don't enter yet) `sudo cp -a /usr/standalone/i386/. /System/Volumes/Preboot/`then paste the text then add this `/System/Library/CoreServices`
(it should look something like this: sudo cp -a /usr/standalone/i386/. /System/Volumes/Preboot/CD844C38-1A25-48D5-9388-5D62AA46CFB8/System/Library/CoreServices)

then you can try the new EFI

**Comment by Lusanta25** [comment]
Lol, yesterday night I have directly tried the new EFI and I haven't noticed any problem with the SecureBootModel and also the ethernet connection now works, thanks mate !

**Comment by SkyrilHD** [comment]
Nice
