### ISSUE TITLE
Internal drive not showing up in macOS installer

### ISSUE THREAD

**Issue by a5th0r** [SkyrilHD/Dell-E7250-Hackintosh#18]
Hi,

I want to install macOS BigSur on my E7250 as well. Same hardware specification as yours.
Booting from the USB into the macOS installer works fine, but I can only select the USB drive and not the internal ssd. 

Do I need a specific BIOS version or BIOS settings?

Best regards,
Gino

**Comment by SkyrilHD** [comment]
Did you change your SATA operation from RAID to AHCI in the BIOS?

**Comment by a5th0r** [comment]
Yes AHCI was set. I had to erase the drive with the drive utility.
