### ISSUE TITLE
little glitches at boot

### ISSUE THREAD

**Issue by newyb** [SkyrilHD/Dell-E7250-Hackintosh#19]

**Comment by newyb** [comment]
Thank you for your work.It works normally in most cases.
But after the system starts, there will be a splash screen.
The notebook needs to go to sleep and wake up again to display normally.
Through the search, I think the problem can be solved by modifying the EDID parameters.
Other models have similar display faults, which are solved by modifying parameters.

Thanks

**Comment by SkyrilHD** [comment]
Can you mention your specs?

Model:
GPU:
Display:

**Comment by newyb** [comment]
Model：E7250（DELL Service Tag：3G58R32）
Intel Core i5-5300U Processor, Integrated HD Graphics 5500,
Display：12.5" Touch FHD (1920 x 1080)
WIFI： Intel Dual Band Wireless-AC 7265AC

**Comment by SkyrilHD** [comment]
Hmm okay a touch screen display... I have the non-touch variant and don't face this issue. Maybe I will look into it. Did you try patching the EDID? My guess is probably the platform-id.

Also I need a confirmation from other users that also have the touch screen variant, so I can know if it is a common issue. Maybe @bobbosit can you confirm this issue?

**Comment by newyb** [comment]
Sorry, I don’t know how to patch the EDID.Because most of the online tutorials are four-leaf clover.
But I can give you a picture with eight apples
I also uploaded the file. You can have a look

[https://github.com/newyb/Something-useful-of-E7250](url)

Thanks

**Comment by SkyrilHD** [comment]
Looking at the pictures.. I found weird things:

The first picture with the glitch at boot is normal. There is nothing wrong with that because the display gets initialised where MacBooks do a fade.

The second picture is weird because everything is glitched except the mouse cursor...

Can you boot to recovery and see if the issue still persists?

**Comment by newyb** [comment]
yeah，every  time you start the machine and enter the login interface, an error will be displayed, including entering the recovery mode.Until you close the monitor cover, wait a few minutes, and then open the notebook.
If I turn on enable legacy option ROMs, it doesn't cost the screen to boot.

I found a similar problem on station Bilibili, the same fault.

[https://www.bilibili.com/video/BV17K4y1b7uN](url)
The video is in Chinese. The main idea at the beginning is as follows:
As soon as the black apple is installed in the notebook, it may appear on the screen when entering the system. At this time, sleep will be normal once, which can be repaired by injecting EDID. (it may be OK to turn on the CSM mode of BIOS, but there are eight apple screens in the second stage)

**Comment by SkyrilHD** [comment]
can you make sure that CSM is enabled, so by disabling Secure Boot?

**Comment by newyb** [comment]
Boot mode is set to UEFI;Secure Boot:OFF

I want to know how you set up BIOS.If I can, I don't want to turn on the CSM.

**Comment by SkyrilHD** [comment]
https://github.com/SkyrilHD/Dell-Exx50-Hackintosh#recommended-bios-settings

check this ^

also why do you not want to enable CSM. Apparently enabling CSM fixes the issue.

**Comment by newyb** [comment]
Sure,apparently enabling CSM fixes the issue except for displaying eight apples at boot.

I don't like CSM because it's not HD, not fast enough, not new enough.Windows 7 can be started by modifying EFI files without CSM.

**Comment by SkyrilHD** [comment]
Ok I found a guide by Sniki which I hope also fixes the issue you have:

https://github.com/Sniki/Lenovo-Thinkpad-T440S#patching-display-edid-wip

Credits to Sniki

**Comment by SkyrilHD** [comment]
Ok, emrah7celik also mentioned another way fixing the glitches which you find here: https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/discussions/6

Thanks to emrah7celik

**Comment by newyb** [comment]
Thanks,I'll try it next week.
The key points are the EDID.
