### ISSUE TITLE
macOS installer quits unexpectedly with ~10 minutes to go, then bootloops

### ISSUE THREAD

**Issue by nunnethan** [SkyrilHD/Dell-E7250-Hackintosh#22]

**Comment by SkyrilHD** [comment]
What is your model, OS you are trying install and BIOS version? Also give more details. How did you create the installer?

**Comment by nunnethan** [comment]
Apologies, pressed "enter" accidentally and submitted the issue without actually writing it. The EFI clearly works for the macOS Recovery environment, and I'm able to erase the target disk fine. When the installer has ~10 minutes left, it "crashes", for want of a better word, but (I expect) tries to boot into the incomplete macOS installation after, and then reboots constantly onto the Apple logo. The macOS version is 11.2.3 and I'm using your latest EFI folder; I built the installer with `createinstallmedia`. My model is an E7250 with a Samsung 128GB SSD and integrated Intel Graphics. I haven't checked the BIOS version but will do so as soon as I can. Thanks for your help! :)

**Comment by SkyrilHD** [comment]
Try adding this boot-arg: `-v debug=0x100 keepsyms=1`
Also make sure you set the BIOS settings correctly

**Comment by nunnethan** [comment]
Thanks for this. I tried again, and the installer completed successfully when the SSD was formatted as APFS (it was formatted as Mac OS Extended previously). Unsure why the installer allowed me to proceed with an incorrectly formatted disk, but there we go... thank you for your help again :)

**Comment by SkyrilHD** [comment]
Glad to hear it worked at the end. :D
