### ISSUE TITLE
Installer wont work without internet...

### ISSUE THREAD

**Issue by tamas123456** [SkyrilHD/Dell-E7250-Hackintosh#26]
Hi! i tried to install macos with this EFI on my latitude 7250 laptop, but the ethernet wont work, i downloaded other kext-s but dont work.... If i try to install macos "An internet connection is requed to install Macos"

**Comment by SkyrilHD** [comment]
what is other kexts?

**Comment by tamas123456** [comment]
LOL, the latest AppleIntele1000e.kext is working, but others dont example: IntelMausi

**Comment by SkyrilHD** [comment]
can you send device and vendor id of ethernet?

**Comment by tamas123456** [comment]
How to view this? i'm now installing the system

**Comment by tamas123456** [comment]
but the download is very very slow, about 1hour and 30minutes, for a 12gb package?

**Comment by SkyrilHD** [comment]
With Hackintool, you can view it: https://github.com/headkaze/Hackintool

Open the app, then go to PCIe and check for network controller

**Comment by SkyrilHD** [comment]
Obviously the download will be slow when you use an unsupported kext

**Comment by tamas123456** [comment]
But, better than nothing :D and after installed, i will check it with this hackintool, thx

**Comment by SkyrilHD** [comment]
alright good luck!

**Comment by tamas123456** [comment]
The android usb hotspot is working with hackintosh?

**Comment by SkyrilHD** [comment]
you need an extra kext called HoRNDIS. If I recall correctly it hasn't been updated for years but give it a try

**Comment by tamas123456** [comment]
Ohh found it, i have a Intel Ethernet I218-LM

**Comment by tamas123456** [comment]
But, this is why dont working with IntelMausi?

    Required for the majority of Intel NICs, chipsets that are based off of I211 will need the SmallTreeIntel82576 kext
    Intel's 82578, 82579, I217, **I218** and I219 NICs are officially supported
    Requires OS X 10.9 or newer, 10.6-10.8 users can use the IntelSnowMausi instead for older OSes

**Comment by SkyrilHD** [comment]
Which version of the EFI are you using? Also, try redownloading the EFI, maybe the download is corrupted

**Comment by tamas123456** [comment]
Bruh, i started from zero, and now fully working, and installed horndis, and WOW, Working perfectly with my Mi 9 SE, thx for you help :)

**Comment by tamas123456** [comment]
Hi! The wifi is fully working now with Big Sur, and the latest itlwm.kext 2.0.0 alpha, with HeliPort app, so very nice
