### ISSUE TITLE
Broadcom Wifi DW1820a not working

### ISSUE THREAD

**Issue by ghost** [SkyrilHD/Dell-E7250-Hackintosh#28]
At first, thank you for this great project, it was really helpful and i appreciate the work you put into it. I installed MacOS on my DELL but Intel Wifi drops to 1-2 Mbps sometimes, so i baught the DW1820a card. I disabled the Airportltlwm.kext, IntelBluetoothFirmware.kext and IntelBluetoothInjector.kext. I added the requiered kext following this guide https://github.com/osy/HaC-Mini/issues/91#issuecomment-546666194 and eddited config.plist but my DELL gets stuck at Mac OS loading screen at around 50%.

**Comment by SkyrilHD** [comment]
Make sure the order is correct:

1. BrcmBluetoothInjector
2. BrcmFirmwareData
3. BrcmPatchRAM3


Note to 3:
- BrcmPatchRAM.kext: for 10.10 or earlier.

- BrcmPatchRAM2.kext: for 10.11 - 10.14.

- BrcmPatchRAM3.kext: for 10.15 or later.

**Comment by ghost** [comment]
Thanks for your prompt answer.
The BrcmBluetoothInjector, BrcmFirmwareData, BrcmPatchRAM3 are in the correct order. I was able to boot now but only with AirportBcrmFixup disabled. Is there anything in this EFI that conflicts iwth AirportBcrmFixup.kext maybe?

**Comment by SkyrilHD** [comment]
Can you try removing this entry from config.plist>DeviceProperties>Add: PciRoot(0x0)/Pci(0x1C,0x3)/Pci(0x0,0x0)

**Comment by ghost** [comment]
I tried everything but couldn't get my card working on big sur. I switched to Catalina and now i have got 2,4 ghz wifi at least
