### ISSUE TITLE
Struggling installing 10.14 

### ISSUE THREAD

**Issue by Lusanta25** [SkyrilHD/Dell-E7250-Hackintosh#31]
Hi @SkyrilHD , I need your help. Those days I have tried to restore my dell-hack that has got right now Big Sur running wit OC without any issues but I wanna give it to my dad  so I need to restore it and downgrade to 10.14 . 
The problem comes right now, because when I select from the BIOS the USB containing the Mojave Installer and the right EFI (obviously  the one for Clover) the pc runs it and later got stuck in a sort of apple boot logo screen but the progress bar doesn't seem to show up at any time.  I will attach a picture right below in order to explain better my situation. 
Have you got any advice ? 
Cheers, Luca. 
![IMG_3895](https://user-images.githubusercontent.com/60262306/128399787-770d80fb-ffdf-4041-a8db-f96022ae49dc.jpg)

**Comment by SkyrilHD** [comment]
Can you try the OpenCore EFI from last month? https://github.com/SkyrilHD/Dell-E7250-Hackintosh/releases/tag/v2.8

This should work without an issue. I haven't updated Clover for a long time, so I cannot really say what is wrong with it.

**Comment by SkyrilHD** [comment]
Any update?

**Comment by Lusanta25** [comment]
Solved, it worked out perfectly! Thank you so much!
