### ISSUE TITLE
WIFI/Bluetooth/Key Bindings / sound / not charging /not Working on BigSur 11.6

### ISSUE THREAD

**Issue by devsurajrai** [SkyrilHD/Dell-E7250-Hackintosh#37]
I just updated the BigSur to 11.6 and found that the wifi is not working. Cannot toggle wifi/bluetooth on or off.  Used proper tree to activate all the kexts by using OC Spapshot option. I don't know if i am doing anything wrong.

**Comment by SkyrilHD** [comment]
I just upgraded to 11.6 and everything works as is. Check your BIOS settings in case you disabled some stuff by accident.

I suggest you enabling WiFi and Bluetooth manually (change false to true).

Bluetooth:
https://github.com/SkyrilHD/Dell-E7250-Hackintosh/blob/06b1ba7cf36cbb1d4b093de18eb30c54f5cfec2b/OpenCore/EFI/OC/config.plist#L840
https://github.com/SkyrilHD/Dell-E7250-Hackintosh/blob/06b1ba7cf36cbb1d4b093de18eb30c54f5cfec2b/OpenCore/EFI/OC/config.plist#L858

WiFi:
https://github.com/SkyrilHD/Dell-E7250-Hackintosh/blob/06b1ba7cf36cbb1d4b093de18eb30c54f5cfec2b/OpenCore/EFI/OC/config.plist#L876

If WiFi still doesn't work, download [itlwm](https://github.com/OpenIntelWireless/itlwm/releases) (in pair with [HeliPort](https://github.com/OpenIntelWireless/HeliPort/releases)) and use it that way.

Sound, Key bindings (I assume you mean F11 and F12) and AC Adapter should work OOTB.

**Comment by SkyrilHD** [comment]
Any update?

**Comment by devsurajrai** [comment]
Yes! I updated Monterey. Everything is working fine. Bluetooth also seems stable this time.Gestures are better than it was in big sure. Thank You So much.

**Comment by SkyrilHD** [comment]
Thank you very much for your feedback! Will closing this issue as it is fixed
