### ISSUE TITLE
VoodooI2C broken on Latest (Version 2.11) OC

### ISSUE THREAD

**Issue by BujuHackTosh** [SkyrilHD/Dell-E7250-Hackintosh#39]
Touch screen is no longer working on the latest Bootloader, tried using the previous version one booting from USB EFI and it worked.

**Comment by SkyrilHD** [comment]
Did you enable VoodooI2C in the config including the plugins?

**Comment by BujuHackTosh** [comment]
Yes, they are all enabled

**Comment by SkyrilHD** [comment]
That's weird. I haven't touched VoodooI2C since 2.4. I also don't have the touchscreen model, so I can't do any debugging.

Could you save an .ioreg with IORegistryExplorer and send it here?

**Comment by BujuHackTosh** [comment]
Sure!
[MacBook Pro.ioreg.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/7325453/MacBook.Pro.ioreg.zip)

**Comment by SkyrilHD** [comment]
At first glance, it looks normal to me. (Maybe an ioreg of working touchscreen would help more) However, I see a device which I have never seen before: "Atmel maXTouch". I guess this is the touchscreen. This seems to be connected via USB. I also see that FakePCIID is enabled. Disable FakePCIID (incl. XHCI_Mux) and USBInjectAll then enable USBMap.kext. Also, don't forget to disable XhciPortLimit as well.

**Comment by BujuHackTosh** [comment]
Fixed, did an OC Snapshot while injecting USBMap kext and it detected a problem with VODOO, which it automatically fixed,

**Comment by SkyrilHD** [comment]
Glad it is fixed... So, is there an issue with EFI because you said "detected a problem with VODOO"

**Comment by BujuHackTosh** [comment]
I guess I'll have to boot with the OC from a flash drive to ascertain if the problem is with the EFI or not, then I'll report my findings.
