### ISSUE TITLE
Does it harm the battery life?

### ISSUE THREAD

**Issue by catalinabigsur** [SkyrilHD/Dell-E7250-Hackintosh#43]
It isn't about the EFI, but how many hour that your laptop use without charge? I'm using the E7450 and it's around 2 hours of battery life On System Information, it said my battery full capacity is 3954mah.

**Comment by SkyrilHD** [comment]
My E7250 has a 52Wh battery and according to macOS 4431mAh. It holds up 3 hours with web browsing. But my battery has degraded a lot. I remember hitting 5:30h on Catalina, so yeah. In general, I get more battery than on Windows
