### ISSUE TITLE
an error occurred loading the update

### ISSUE THREAD

**Issue by 83435** [SkyrilHD/Dell-E7250-Hackintosh#44]
I am trying fresh install and getting this error everytime in recovery. Can u pls help me!

**Comment by SkyrilHD** [comment]
Sorry but this does not help at all... Describe your issue in detail e.g. which EFI version you are on, what OS you are trying to install, etc.

**Comment by 83435** [comment]
i am trying Monterey using latest efi for macos 12. i create the installer in vm and then when i boot it loads till 12 mins remaining and then shows an error occurred  loading the update

**Comment by 83435** [comment]
this is only the whole thing

**Comment by SkyrilHD** [comment]
Double check your BIOS settings: https://github.com/SkyrilHD/Dell-Exx50-Hackintosh#recommended-bios-settings

If it still doesn't work, then it might be your installer is broken. Install Big Sur and create an installer from there (with the last EFI update). Since Monterey is new, there is no Recovery installer yet, so you need to recreate the full installer (not on a VM)

**Comment by 83435** [comment]
i tried recovery as it has been now added but still no luck it gets stuck at 13 mins remaining and then shows same error

**Comment by SkyrilHD** [comment]
Did you format the drive as APFS with GPT?

**Comment by 83435** [comment]
> Did you format the drive as APFS with GPT?

yes

**Comment by 83435** [comment]
i will try new efi

**Comment by 83435** [comment]
same thing. do u have discord where i can seek your help!

**Comment by 83435** [comment]
i was thinking it can be wifi issue but i opened the safari in recovery and it was working

**Comment by SkyrilHD** [comment]
Sorry, I don't know what issue exactly is, so I don't think discord might be helpful.

I did a clean install myself and it worked without an issue.

My last idea would be to re-create the installer.

**Comment by 83435** [comment]
i tried that like 3 times

**Comment by 83435** [comment]
I think i will buy a msata to usb and connect to mac and install it and then plug ssd in laptop and mount efi.
Tell me if it is possible

**Comment by SkyrilHD** [comment]
should be possible

**Comment by 83435** [comment]
ok thnx bud

**Comment by 83435** [comment]
i ordered the enclosure it will arrive in 2-3 days i will update you

**Comment by 83435** [comment]
ok it worked
thnx bud for awesome work
