### ISSUE TITLE
Microsoft Excel show error when work with data

### ISSUE THREAD

**Issue by n2ng-dev** [SkyrilHD/Dell-E7250-Hackintosh#45]
Hi,, 
Thanks for your amazing work,
I got issue with Microsoft Excel, always show error "There isn't enough memory to complete this action", I use Last update of MS. Office, my memory 8GB, 
In BigSur can work fine.

![image](https://user-images.githubusercontent.com/12078569/139379047-b8f815f1-77c5-44d2-9cc2-832d47d3de02.png)

**Comment by SkyrilHD** [comment]
Not related to EFI. Contact Microsoft instead.
