### ISSUE TITLE
bluetooth

### ISSUE THREAD

**Issue by gaslarfa** [SkyrilHD/Dell-E7250-Hackintosh#47]
In the folder there are 2 kext referring to bluetooth.
Could you tell me which one should I enable?

**Comment by SkyrilHD** [comment]
Both

EDIT: IntelBluetoothFirmware and BlueToolFixup to be exact

**Comment by gaslarfa** [comment]
prefect that way i did it.
Another question... You know why it does not pair with my iphone but with other devices it does?

**Comment by SkyrilHD** [comment]
Afaik you need to confirm to allow access from your iPhone.

**Comment by gaslarfa** [comment]
I do it but it comes back and unravels
