### ISSUE TITLE
Battery not charging

### ISSUE THREAD

**Issue by proschnoss** [SkyrilHD/Dell-E7250-Hackintosh#49]
Hello sir @SkyrilHD  i want to thanks to you for all your hard works.. I really appreciate it. But after i used monterey hackintosh on my e7250 5300u.. I realize last night when my battery go for 6% it still and it won't to charge the batteries. The battery before install this hackintosh can last for more than 3h. But suddenly cant charge. I go for bios menu battery condition is in good level.. But on monterey it shows to service battery.

Thanks for your attention..

**Comment by SkyrilHD** [comment]
Sounds like a faulty battery to me. Does it charge in the BIOS or in Windows/Linux? Tried replugging the battery?

macOS will always show "Service battery" as it is a bug in VirtualSMC.

**Comment by proschnoss** [comment]
Hey thank you for your replyy,, no i dont try to charge on windows cause my ssd only 128gb.. I try to charge it on bios but still not charging. I do to repkugging batteries but still same case not charging,, monterey only shows plugged in,, and battery indicator when plugged in only blinking once

**Comment by SkyrilHD** [comment]
Leave it plugged in for a longer time, e.g. overnight. If nothing works, then it's a faulty battery.

**Comment by proschnoss** [comment]
wow nice advice ,, that's worked !! 
i charge iver 8hour and now its charging ,, thank you sir @SkyrilHD 
thanks to you i recently cancel my order on e-commerce for dell batteries 
nice job 
#joss

**Comment by SkyrilHD** [comment]
I'm glad to hear that!

I will put "invalid" as it was not an issue with the EFI.
