### ISSUE TITLE
Bluetooth not working

### ISSUE THREAD

**Issue by Lusanta25** [SkyrilHD/Dell-E7250-Hackintosh#5]
Hello, I have a problem with the EFI that you have given us... I don't understand how to enable bluetooth on the Intel card (the AC7265) one!
I have successfully made into catalina desktop but can't enable the bluetooth =(
Pls help me =)

**Comment by SkyrilHD** [comment]
It's should already be activated

**Comment by Lusanta25** [comment]
Where I should check it ?

**Comment by SkyrilHD** [comment]
Open system preferences and go to Bluetooth

**Comment by Lusanta25** [comment]
I couldn't find it .. if you give me ten minutes I will send you a picture :) 
okay I've checked it and there isn't ... any advice?

**Comment by SkyrilHD** [comment]
Can you open System Profiler and look in Bluetooth and USB if there is something missing. If yes, did you boot off of the EFI that I provided

**Comment by Lusanta25** [comment]
Yes I have booted with the EFI that you have provided... look at the picture down here
![photo_2020-04-20 13 25 52](https://user-images.githubusercontent.com/60262306/79746572-7ee3ee80-830a-11ea-8e43-9f61cf35f812.jpeg)

**Comment by SkyrilHD** [comment]
1. Make sure your Wireless is on (on/above the keyboard there should be a light)
2. This is the network settings, go to the main page and there should be a dedicated Bluetooth section

**Comment by Lusanta25** [comment]
you are a boss... it works
How I can enable now airdrop?

**Comment by SkyrilHD** [comment]
Sadly, you can't... because AirDrop also depends on WiFi which doesn't work for our devices

**Comment by Lusanta25** [comment]
also continuity doesn't work?

**Comment by SkyrilHD** [comment]
Won't work too

**Comment by SkyrilHD** [comment]
Btw if the issue is done, please close it thanks

**Comment by Lusanta25** [comment]
should I try to make work the intel wifi card?

**Comment by SkyrilHD** [comment]
There are devs that are working on Intel WiFi:

zxystd/itlwm
AppleIntelWifi/adapter (by mainly hatf0)

You can go on the internet but no AirDrop ;D

**Comment by Lusanta25** [comment]
what are the devs ? ... sorry for my ignorance on the matter😅

**Comment by SkyrilHD** [comment]
zxystd and AppleIntelWiFi
search that on Google; both different projects

**Comment by Lusanta25** [comment]
okay, I will keep you up on the matter

**Comment by Lusanta25** [comment]
I won't try this stuff because I am afraid that I'll ruin everthing

**Comment by Lusanta25** [comment]
hey dude what is Karabiner config?

**Comment by SkyrilHD** [comment]
You can't natively turn down or up the brightness, so I provided a Karabiner config (which need the Karabiner app) to make native brightness control working.

**Comment by Lusanta25** [comment]
I can't get it working but no problem I will use the BIOS display regulation option

**Comment by Lusanta25** [comment]
@SkyrilHD I need your help ... I have the same typology of PCI interface on both the Dell Latitude Hack but also on a Hp Desktop Hack if I replace the one on the Hp with the one in the Dell the bluetooth should it work immediately or shall I put some kexts in the EFI folder?

**Comment by SkyrilHD** [comment]
It depends what card it is

**Comment by Lusanta25** [comment]
it is the old card of the dell that I wanna put on the HP Desktop
The one that you also have on the dell laptop hack

**Comment by SkyrilHD** [comment]
Copy IntelBluetoothFirmware.kext and IntelBluetoothInjector.kext to the HP's EFI partition. Whether it will work... I don't know.

**Comment by Lusanta25** [comment]
oke, I'll try and let you know.

**Comment by Lusanta25** [comment]
oh man it works... thanks !
