### ISSUE TITLE
Reinstall instead of Install

### ISSUE THREAD

**Issue by bokie1** [SkyrilHD/Dell-E7250-Hackintosh#50]
Hi, I followed everything and tried loading the USB but it says Re-Install instead of Install.
When I click re-install, it says it needs internet to install MacOS.
I'm lost now.

**Comment by SkyrilHD** [comment]
It is normal for the Online Recovery Installer to say "Reinstall". It is a generic term used by Apple.

Online recoveries require internet to download the full OS. Either connect via LAN or via Wi-Fi (make sure you enabled AirportItlwm in the config).

**Comment by bokie1** [comment]
> It is normal for the Online Recovery Installer to say "Reinstall". It is a generic term used by Apple.
> 
> Online recoveries require internet to download the full OS. Either connect via LAN or via Wi-Fi (make sure you enabled AirportItlwm in the config).

How do I enable it? Because it says enabled, unless I'm looking at the wrong config.

	<key>Arch</key>
				<string>x86_64</string>
				<key>BundlePath</key>
				<string>AirportItlwm.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<false/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/AirportItlwm</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>

**Comment by SkyrilHD** [comment]
After Enabled it says: False. Change it to: True

So ist looks like this:
```
<key>Enabled</key>
<true/>
```

**Comment by bokie1** [comment]
> After Enabled it says: False. Change it to: True
> 
> So ist looks like this:
> 
> ```
> <key>Enabled</key>
> <true/>
> ```

got it. Thanks.
By the way, why is it that it needs the USB all the time in order to boot to MacOS? When I remove the USB, it says no bootable media.

**Comment by SkyrilHD** [comment]
After installation you need to copy the folder which you used for USB onto the hard drive.

1. Open Terminal
2. Type `diskutil list`

You will see a list of partitions. You need to look for "EFI" and "IDENTIFIER". Mine would be disk0s1.

3. Now mount the EFI Partition by typing this command: `sudo diskutil mount disk0s1` (Change 0 and 1 if yours is different)
4. You should see an EFI Partition in Finder. Copy the EFI folder from the USB stick to the EFI Partition of the hard drive.

**Comment by bokie1** [comment]
> 4\. USB stick

Thanks. Found the issue. I only copied BOOT AND OC instead of copying EFI to EFI. 
Thanks again

**Comment by bokie1** [comment]
> After installation you need to copy the folder which you used for USB onto the hard drive.
> 
> 1. Open Terminal
> 2. Type `diskutil list`
> 
> You will see a list of partitions. You need to look for "EFI" and "IDENTIFIER". Mine would be disk0s1.
> 
> 3. Now mount the EFI Partition by typing this command: `sudo diskutil mount disk0s1` (Change 0 and 1 if yours is different)
> 4. You should see an EFI Partition in Finder. Copy the EFI folder from the USB stick to the EFI Partition of the hard drive.

One last thing,
 When I open and logged in to iMessage, it logs me out. Also, I can't log into Facetime.
Already tried replacing the SMBOIS info to an invalid one but still the same results.

**Comment by SkyrilHD** [comment]
I cannot say why it happens as it works for me perfectly. But try following this guide: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html

**Comment by marioeagle93** [comment]
> 4. You should see an EFI Partition in Finder. Copy the EFI folder from the USB stick to the EFI Partition of the hard drive.

Hello there! I found this thread that guided me through basically every same mistake I did. Now I'm stuck here:

I installed everything on the local SSD and I want to copy everything to the EFI folder. I mounted the EFI partition but I cannot copy any file from any folder in finder. Do you have any hint on that?
Thanks.

**Comment by SkyrilHD** [comment]
Sounds like the EFI partition is in read-only mode. Tried rebooting? Maybe try to copy the EFI in Windows/Linux.

**Comment by marioeagle93** [comment]
Ok I managed to copy files to the EFI partition via Ubuntu live USB disk. Now the bootloader is actually loading macos but I'm stuck in a bootloop: I press the on button, I see Dell logo, then Apple logo, after about 20 seconds the system shuts down and restarts. I tried changing boot options but still nothing.

**Comment by SkyrilHD** [comment]
That is very weird. The EFI cannot break itself if you did not change anything to it. Sounds like the EFI got corrupted. Also add -v to boot-args.

**Comment by marioeagle93** [comment]
I tried performing a fresh install again: after the installation the system shuts off and reboot automatically. I don't know whether this is a good thing or not, like if user should be warned for reboot.
Then on the bootloader I see the Mac drive (golden one) and I click on it. Right after it seems like something is loading, then the system shuts down and goes back to the boot options, but this time I only see Mac recovery. What am I missing?

**Comment by SkyrilHD** [comment]
Try these following things:

1. Make sure you formatted the drive as GPT and APFS (not Mac OS Journaled aka HFS+)
2. Clear the NVRAM
3. As far a I know, until you get into the setup, the system will reboot 4-5 times. Just boot into the Volume called 'Macintosh HD' until you reach the setup.
4. Double check your BIOS settings
5. Recreate the installer
6. Download the installer again
7. Verbose mode (boot-args: -v) will help you to debug the issue
8. Redownload the EFI

**Comment by marioeagle93** [comment]
It works now! I guess the problem was either related to bios settings or drive not formatted to APFS. Thank you very much for your help, your quick replies, and for sharing all of your work!

**Comment by SkyrilHD** [comment]
Glad to hear it worked for you in the end, and thanks for the feedback! I appreciate it.

Closing issue.
