### ISSUE TITLE
Battery: malfunctioning battery indicator

### ISSUE THREAD

**Issue by devsurajrai** [SkyrilHD/Dell-E7250-Hackintosh#52]
Battery indicator is not showing realtime updates. It suddenly drops from suppose 80% to 10% which causes inconvenience.
You can find the screenshot attached below. At this point of time the battery is removed but still it is showing charging.
Please address the issue if possible. Thanks for the fully working mac os and keeping it updated all the time. Kudos to you.

![Screenshot 2022-03-16 at 10 59 38 AM](https://user-images.githubusercontent.com/77954411/158522872-b65c3122-5d14-4f36-8464-f91af8fee7b1.png)

**Comment by SkyrilHD** [comment]
Hmm. I don't have the issues you mentioned on my system. I suspect the battery is old and probably needs to be replaced.  My battery discharges in 3h and charges in 2h.  But I use a 130W power supply.  For your charging issues, check your BIOS settings because afaik you can change the charging speed.

**Comment by devsurajrai** [comment]
> Hmm. I don't have the issues you mentioned on my system. I suspect the battery is old and probably needs to be replaced. My battery discharges in 3h and charges in 2h. But I use a 130W power supply. For your charging issues, check your BIOS settings because afaik you can change the charging speed.

Thanks for getting back on this. But I just replaced my battery thinking the first replaced one was faulty i replaced it again. Anyways I will check the BIOS as suggested. Closing the issue.
