### ISSUE TITLE
Volume Hash Mismatch

### ISSUE THREAD

**Issue by devsurajrai** [SkyrilHD/Dell-E7250-Hackintosh#54]
I installed the latest "macOS Monterey 12.3" and this weird error "Volume Hash Mismatch. macOS should be reinstalled on this mac". Also the macOS restarts randomly. Please provide the resolution for the same if your time permits. Thank you so much. Kudos to you.

**Comment by SkyrilHD** [comment]
Sadly, nothing I can do about it. This issue also persists on real Macs. Hopefully Apple fixes it with an update.

**Comment by devsurajrai** [comment]
Thanks ! looking forward to it.
