### ISSUE TITLE
Random issue trackpad after restart

### ISSUE THREAD

**Issue by n2ng-dev** [SkyrilHD/Dell-E7250-Hackintosh#55]
Version 3.5
OS 12.3 (21E230)

I got random issue trackpad doesn't work after restart,

**Comment by SkyrilHD** [comment]
Will work on a fix.

You can temporarily "downgrade" to the old ALPS kext. [Link](https://www.github.com/SkyrilHD/VoodooPS2-ALPS/releases)

**Comment by SkyrilHD** [comment]
@Nanank-kho Can you try this? https://github.com/SkyrilHD/VoodooPS2/actions/runs/2385031854
