### ISSUE TITLE
Random Restarts

### ISSUE THREAD

**Issue by devsurajrai** [SkyrilHD/Dell-E7250-Hackintosh#58]
Random restart happens. I am currently on 12.3 Monterey. Please suggest some fix.

**Comment by SkyrilHD** [comment]
Provide logs.

**Comment by devsurajrai** [comment]
> Provide logs.
![Screenshot 2022-04-16 at 12 41 00 PM](https://user-images.githubusercontent.com/77954411/163665590-f76b726e-fe50-4871-9943-71849a7665af.png)
Which log file do you need out of this ss?

**Comment by SkyrilHD** [comment]
Kernel Panic Log which I don't see

**Comment by devsurajrai** [comment]
> 

These are the only logs which are present in the console

**Comment by SkyrilHD** [comment]
Well, none of these logs are useful. I'm on 12.3 Beta and I have not encountered random reboots yet.

**Comment by devsurajrai** [comment]
> Well, none of these logs are useful. I'm on 12.3 Beta and I have not encountered random reboots yet.

IDK what's wrong with mine. I always need to run the command 'sudo purge' to avoid volume mismatch issue.

**Comment by SkyrilHD** [comment]
Volume mismatch also happens on my system. I can mostly trigger it by running Xcode under load. Then I get the notification and everything turns black until I restart. This is the only way I can trigger it, else it works fine. To avoid this behaviour downgrade to Big Sur, I guess. Nothing I can do about it as it happens on native Macs as well. You need to wait for Apple to fix this bug.

**Comment by devsurajrai** [comment]
> Kernel Panic Log which I don't see
Please see if this is the log you need: 

panic(cpu 0 caller 0xffffff801bfd38f3): Kernel trap at 0xffffff8020121a0e, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0xffffff8b6aa566f8, CR3: 0x0000000027f11000, CR4: 0x00000000003626e0
RAX: 0x0000000000000000, RBX: 0x00000000ffffffff, RCX: 0x00000000000002d5, RDX: 0x00000000000004af
RSP: 0xffffffd023adbdb0, RBP: 0xffffffd023adbdb0, RSI: 0x00000000000004af, RDI: 0xffffff8b6aa55000
R8:  0x0000000000000000, R9:  0xffffff8b6aa54fb8, R10: 0x00000000000002d5, R11: 0xfffffffffffffff7
R12: 0x0000000000000000, R13: 0xffffff8b6aa55000, R14: 0xffffff8b6aa551a2, R15: 0xffffffd023adbe40
RFL: 0x0000000000010206, RIP: 0xffffff8020121a0e, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0xffffff8b6aa566f8, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0, VF: 10

Panicked task 0xffffff9037492670: 179 threads: pid 0: kernel_task
Backtrace (CPU 0), panicked thread: 0xffffff9504aa0550, Frame : Return Address
0xffffffd023adb760 : 0xffffff801be83e2d 
0xffffffd023adb7b0 : 0xffffff801bfe3cb6 
0xffffffd023adb7f0 : 0xffffff801bfd350d 
0xffffffd023adb840 : 0xffffff801be23a60 
0xffffffd023adb860 : 0xffffff801be841fd 
0xffffffd023adb980 : 0xffffff801be839b6 
0xffffffd023adb9e0 : 0xffffff801c7164bf 
0xffffffd023adbad0 : 0xffffff801bfd38f3 
0xffffffd023adbc50 : 0xffffff801bfd35e2 
0xffffffd023adbca0 : 0xffffff801be23a60 
0xffffffd023adbcc0 : 0xffffff8020121a0e 
0xffffffd023adbdb0 : 0xffffff802012087e 
0xffffffd023adbe30 : 0xffffff8020122014 
0xffffffd023adbea0 : 0xffffff802012354c 
0xffffffd023adbed0 : 0xffffff801c647454 
0xffffffd023adbf20 : 0xffffff801c645d0e 
0xffffffd023adbf60 : 0xffffff801c645337 
0xffffffd023adbfa0 : 0xffffff801be2318e 
      Kernel Extensions in backtrace:
         as.acidanthera.voodoo.driver.PS2Trackpad(2.2.8)[A54250A9-E83D-3B7A-BFF5-96FF47975BD0]@0xffffff802011b000->0xffffff802013dfff
            dependency: as.acidanthera.voodoo.driver.PS2Controller(2.2.8)[E72A38F2-CDC4-3E4F-85BE-C94041B39DCC]@0xffffff80200f5000->0xffffff802010cfff
            dependency: com.apple.iokit.IOHIDFamily(2.0.0)[07A59F85-E546-3A79-A875-4C1AB49407DB]@0xffffff801e69d000->0xffffff801e6f9fff

Process name corresponding to current thread (0xffffff9504aa0550): kernel_task
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
21E258

Kernel version:
Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
Kernel UUID: B6F8637B-0844-355F-8C82-60FA06149384
KernelCache slide: 0x000000001bc00000
KernelCache base:  0xffffff801be00000
Kernel slide:      0x000000001bc10000
Kernel text base:  0xffffff801be10000
__HIB  text base: 0xffffff801bd00000
System model name: MacBookPro12,1 (Mac-E43C1C25D4880AD6)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 19299950213184
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000118d9ead3d43
  Sleep   : 0x00000da21257797c 0x0000000080808175 0x00000d95797fa259
  Wake    : 0x00000da216285c76 0x000000007ecca333 0x00000da212a4e54e
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Foreign : 0xffffff802832c000 - 0xffffff802833a000
  Native  : 0xffffff80374d3000 - 0xffffffa0374d3000
  Readonly: 0xffffff850419f000 - 0xffffff869db38000
  Metadata: 0xfffffff7ef547000 - 0xfffffff80f639000
  Bitmaps : 0xfffffff80f639000 - 0xfffffff813239000

**Comment by devsurajrai** [comment]
> Volume mismatch also happens on my system. I can mostly trigger it by running Xcode under load. Then I get the notification and everything turns black until I restart. This is the only way I can trigger it, else it works fine. To avoid this behaviour downgrade to Big Sur, I guess. Nothing I can do about it as it happens on native Macs as well. You need to wait for Apple to fix this bug.

Yaa ! lets hope for it to happen asap.

**Comment by SkyrilHD** [comment]
@devsurajrai Can you try the kext? https://github.com/SkyrilHD/VoodooPS2/actions/runs/2385031854

**Comment by devsurajrai** [comment]
> @devsurajrai Can you try the kext? https://github.com/SkyrilHD/VoodooPS2/actions/runs/2385031854

Sure ! Would it stop the random restarts?

**Comment by SkyrilHD** [comment]
I have been using it for months. Did experience any panic yet. An overall feedback would be great :)

**Comment by devsurajrai** [comment]
> I have been using it for months. Did experience any panic yet. An overall feedback would be great :)

Hello Brother ! I have been testing the above kext you asked to but gestures aren't great on that. I guess i would have to switch on old one

**Comment by devsurajrai** [comment]
> I have been using it for months. Did experience any panic yet. An overall feedback would be great :)

Overall its working just great. I only face issue with random shut down, trackpad (three finder drag is glitchy) and bluetooth dosen't work properly(dosen't work after sleep). Thank for taking out your time and working on this project. Your'e a rockstar.

**Comment by SkyrilHD** [comment]
Which gestures are not great with the new kext, so I can fix it? The random shut down you issue should be fixed with the new kext as well. For Bluetooth, type this in terminal every time after wake: sudo killall -9 bluetoothd BlueTool

**Comment by devsurajrai** [comment]
> Which gestures are not great with the new kext, so I can fix it? The random shut down you issue should be fixed with the new kext as well. For Bluetooth, type this in terminal every time after wake: sudo killall -9 bluetoothd BlueTool

Issues that I feel are there:
- the touch sensitivity of the trackpad is not up to the mark. Like I really have to tap the trackpad hard. 
- Gestures like three finger drag does not behave controlled.
- The trackpad pointer sometimes jumps somewhere else

https://user-images.githubusercontent.com/77954411/171437463-b64e132d-f10c-415e-8068-37f62c1c6f51.mov

These are the ones I use and noticed. Please see if you can fix them. Thanks alot  brother.

**Comment by SkyrilHD** [comment]
That's very odd. Personally, the kext is the same as acidanthera's version but with improved stability (which was my aim). Which version of kext are we comparing, so I can compare it with my touchpad?

**Comment by devsurajrai** [comment]
> That's very odd. Personally, the kext is the same as acidanthera's version but with improved stability (which was my aim). Which version of kext are we comparing, so I can compare it with my touchpad?

I am comparing the current one with improved stability with the latest updated kexts release (maybe 2-3 months back you updated). although three finger drag issue was persists in both of them.

**Comment by SkyrilHD** [comment]
3+ fingers will never be resolved as the touchpad is really, really bad at distinguishing fingers. It happens on Linux as well. Sadly, nothing I can fix on my end.
