### ISSUE TITLE
Dimmed screen when booting Windows 11 through OpenCore

### ISSUE THREAD

**Issue by adyrosebrigg** [SkyrilHD/Dell-E7250-Hackintosh#62]
Hi, I recently hackintoshed my e7250 using this repo as a base, and I love it! Everything's working perfectly in macOS Monterey. This is a Windows issue, so I'm not especially expecting to have it addressed, more just wondering if anybody else has noticed it and might have ideas for a fix.

My issue is that now, when booting Windows 11 through OpenCore (0.8.0) with this configuration, the screen is initially dimmed on startup. Specifically, the screen seems to use my bios brightness settings (100% on AC, 70% on batt) throughout the boot process as expected; but then when Windows enters the GUI and shows the lock/login screen, brightness is set to very dim--I would guess about 10%. This is instantly corrected when modifying the brightness: pressing either brightness key brings brightness back to expected levels, seemingly automatically bumping brightness to the last value used during boot before adjusting it.

The issue only occurs when booting through OpenCore. If I use the uefi boot selector to directly boot the Windows boot manager, bypassing OpenCore, everything works normally. So it's a minor issue that I can easily work around, but it compels me, and if possible I'd like to be able to just use OpenCore as my sole boot manager for macOS, Windows, and Linux (as I do on my other hackintosh, a desktop).

This is something I've never seen Windows do before, and google wasn't especially helpful in troubleshooting it. Theories I have that might be starting points to figuring this out:
- Maybe I changed something in the config.plist that caused this?
  - I don't think this is the case, as I just now re-downloaded the config.plist from this repo and booted it nearly as provided; the only modification is my generated smbios/rom/etc.
- Maybe my smbios is the problem?
  - When I generated my smbios, I used MacBook10,1 (no reason in particular, the e7250 just seems like an entry level compact laptop to me so I picked the closest MacBook I could find in terms of hardware as a base. If others are using MacBookPro12,1 as in the supplied plist and not having this issue, maybe that's the cause.
- Is it Windows 11-specific or specific to the drivers Windows Update installs?
  - I only have an installer lying around for 11, so I haven't tested to see if 10 reproduces this issue on my hardware, but I have tried reinstalling 11 from scratch and the issue starts happening upon the first reboot after Windows is fully installed. It doesn't happen during any of the reboots *during* the windows install, though, so it seems to be caused by a driver or driver configuration that is installed (probably by Windows Update) during the final installation stage... or by some other code that only gets executed when the login screen is shown.
- Something else?

Again, I'm not expecting this to get fixed and you can close the issue if it's not appropriate, but if anyone has any ideas for isolating or fixing the problem, I'm happy to work to figure it out. Thanks for your time and thanks for this repo!

**Comment by SkyrilHD** [comment]
Thanks for the very detailed response! The EFI I provide is the same I use daily (except serial number etc.). When I had a Windows 10 & Windows 11 installation ('had' because Windows killed itself for whatever reason), I did not face this issue at all. Maybe check if you are running the latest BIOS version, which I believe is A24. Double-check your BIOS settings as well: [Link](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh#recommended-bios-settings)

Do you have the 1080p or the 768p model?

I will leave this issue open for visibility.

**Comment by adyrosebrigg** [comment]
I just checked my bios settings and they were exactly as listed in the repo you linked; bios version was A24 as well, as I made sure to update it to that before setting everything up.

I do have the 768p display, so it might come down to that. I actually have a used 1080p/touch display unit from another e7250 coming by way of ebay for an upgrade soon, so when I change that out I'll let you know if that fixes it!

**Comment by adyrosebrigg** [comment]
Hey, I just received and installed that 1080p display and can confirm that I'm still having the dim screen on boot issue. Touch works fine OOTB, so presumably Windows pulled whatever drivers it felt it needed for the display upon detection. I may try reinstalling Windows one more time when I have the time, to see if a full wipe fixes whatever configuration issues may be lingering from the old display setup. Like I said in my initial post, it's not the end of the world to have to press one extra key on bootup, so if we can't figure it out, no big deal.

As a side note, one unexpected thing that changing the display did. I was previously having an issue with the provided files where OpenCanopy wasn't being used; I just got the basic text menu to select OSes every time I booted. Also not a huge issue, so I had put off rooting around to fix it until I had some free time some day. But upon changing the display, OpenCanopy started appearing immediately. Unknown if this is due to something in the config, or if perhaps OpenCanopy has a minimum supported resolution and the 768p display is below the threshold.

Interesting nonetheless, and I wanted to mention it for any googlers in the future because while I'm not personally gonna spend an hour each way switching my old display back to debug the problem, **I will note for the record that (for me, at least), OpenCanopy's graphical boot menu works *only* on units with the 1080p display when using this config as provided.**

As a final note, I'm squinting pretty hard in Monterey at 1080p on this relatively small display. I read up on UI scaling and supposedly it should be automatic when selecting a non-native res in System Preferences, but when I selected 1600x900 as a happy medium between 1080p and 768p, I found that text was a bit fuzzy. Not sure if I'm imagining it, though. I also don't know a lot about the underpinnings of UI scaling in any OS, but Windows 11 looks good at 125% scale with res set to 1080p, and (again, I may be imagining this...) Monterey looks a little less good. *Shrug.*

Anyways, thanks again for the input and I'll let you know if I find a fix to the dimming issue in the future. Now, I'm off to adjust my kext config to get touch working in Monterey!

**Comment by SkyrilHD** [comment]
> Like I said in my initial post, it's not the end of the world to have to press one extra key on bootup, so if we can't figure it out, no big deal.

I would like to have it fixed, because I hate it when something is broken xD However as I said earlier, the issue did not persist on my E7250. It was a clean install as well.

> As a side note, one unexpected thing that changing the display did. I was previously having an issue with the provided files where OpenCanopy wasn't being used; I just got the basic text menu to select OSes every time I booted. Also not a huge issue, so I had put off rooting around to fix it until I had some free time some day. But upon changing the display, OpenCanopy started appearing immediately. Unknown if this is due to something in the config, or if perhaps OpenCanopy has a minimum supported resolution and the 768p display is below the threshold.

Now I'm wondering if this is due to corrupted EFI files. Sometimes uploading to GitHub can result in corrupted files.
I can confirm that OpenCanopy does work on my 768p model. I will try the GitHub EFI soon to test it.

> As a final note, I'm squinting pretty hard in Monterey at 1080p on this relatively small display. I read up on UI scaling and supposedly it should be automatic when selecting a non-native res in System Preferences, but when I selected 1600x900 as a happy medium between 1080p and 768p, I found that text was a bit fuzzy. Not sure if I'm imagining it, though.

Try to enable HiDPI with this tool: https://github.com/xzhih/one-key-hidpi

**Comment by adyrosebrigg** [comment]
The HiDPI tool worked perfectly, thank you! Default settings look great on my screen.

**Comment by SkyrilHD** [comment]
Could you try disabling all ACPI>Add and ACPI>Patch entries and boot to Windows that way? I don't see what could be causing this issue in any other way.

**Comment by adyrosebrigg** [comment]
Actually, and I have no explanation for why, but: **The issue has disappeared suddenly!** Possibly related to configuration changes I made while addressing [this other issue](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/issues/63#issuecomment-1140366060)? If I get a chance I'll restore a backup of my EFI folder and see if that was the change that did it so maybe we can narrow this down. Either way, thanks for your help!

**Comment by adyrosebrigg** [comment]
Okay, I did some poking around (and a lot of rebooting) and it seems like SSDT-XOSI.aml was what did it! With both my backup config from about a week ago, and my current config, adding or removing XOSI (and making the according change in config.plist) causes the issue to appear/disappear.

For further analysis and to hopefully fix the issue if anyone else down the line has it--the XOSI which fixed the dimming issue for me was:

```ASL
/*
 * Intel ACPI Component Architecture
 * AML/ASL+ Disassembler version 20200925 (64-bit version)
 * Copyright (c) 2000 - 2020 Intel Corporation
 * 
 * Disassembling to symbolic ASL+ operators
 *
 * Disassembly of iASLSczXgO.aml, Wed Jun  1 16:09:14 2022
 *
 * Original Table Header:
 *     Signature        "SSDT"
 *     Length           0x00000059 (89)
 *     Revision         0x02
 *     Checksum         0x05
 *     OEM ID           "OCLT"
 *     OEM Table ID     "OC-XOSI"
 *     OEM Revision     0x00000000 (0)
 *     Compiler ID      "INTL"
 *     Compiler Version 0x20210331 (539034417)
 */
DefinitionBlock ("", "SSDT", 2, "OCLT", "OC-XOSI", 0x00000000)
{
    Method (XOSI, 1, NotSerialized)
    {
        If (_OSI ("Darwin"))
        {
            If ((Arg0 == "Windows 2013"))
            {
                Return (Ones)
            }
            Else
            {
                Return (Zero)
            }
        }
        Else
        {
            Return (_OSI (Arg0))
        }
    }
}
```
and here's a downloadable copy: [SSDT-XOSI.aml.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/8818778/SSDT-XOSI.aml.zip)

@SkyrilHD, it remains to be seen if anyone else has been having this problem or if it's just something specific to my machine or config somehow. If problems arise in the future, I suppose someone will (hopefully) find this issue by googling & let us know. It's resolved for me, so feel free to close the issue if you think that's the best call (this is my first github issue so I don't wanna overstep by closing it preemptively, haha). Again, thanks for all the help!

**Comment by SkyrilHD** [comment]
I appreciate the solution. I remember someone having this issue as well, so it is not specific to your machine. I will release the fix together with the new OpenCore update, until then the issue remains open.
