### ISSUE TITLE
Touchscreen issue on Monterey after display swap

### ISSUE THREAD

**Issue by adyrosebrigg** [SkyrilHD/Dell-E7250-Hackintosh#63]
Hey, I just got a 1080p touch display to upgrade my 768p model. Display looks good and touch works in Windows and Ubuntu, but isn't working in Monterey after enabling the Voodooi2c kexts. Looking to troubleshoot, but not exactly sure where to start.

The relevant facts:

- This display came as a fully assembled top laptop panel which was listed on ebay as being from an e7250. I had no reason to doubt this before, but I'm wondering now if the seller got the model number wrong and this is from a different dell laptop of the same size and similar build. It's definitely compatible with the hardware of the laptop itself, I'm just wondering if maybe it's using a different interface or something than the stock e7250 touch display and that's why it's not working.
- The outside casing of the display itself is different from my stock 768p display. The original was a solid matte black, but this 1080p replacement has a subtle checkerboard pattern. Can anyone who has the e7250 with a stock 1080p touch display confirm whether that's normal or if mine may be from a different model?
- Further detail of this panel assembly that may help identify whether it's from an e7250 or not: the inner display surface is a glossy screen which extends above and below the display itself to encompass the camera area and Dell logo. The glossy screen extends to form nearly the entire bezel, reaching to the top and side edges, and coming to an end about half an inch from the bottom of the assembly with rounded bottom corners.

What i've tried so far:

- Enabling the Voodoo kexts that came with this repo. Voodooinput from Voodoops2 disabled and the one from Voodooi2c enabled. No luck.
- I also tried using the latest release of Voodooi2c; I figure these are the same files as in this repo based on that one having been released back in february, but I tried em anyways. I even included the VoodooI2CAtmelMXT, as I think that's the brand of digitizer included in some other dell laptops, but I also had no luck with that configuration.

All that being said, I'll drop an ioreg if anybody has the time to look at it; I've always been not quite sure what I'm looking for when I open IOregistryexplorer so any help is appreciated. Will also reboot to windows shortly and attach a DSDT. If there's anything else I can provide or check to help figure this out, please let me know! Thanks for your time.

[ady's e7250 ioreg.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/8791861/ady.s.e7250.ioreg.zip)
[ady's e7250 DSDT.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/8791866/ady.s.e7250.DSDT.zip)

(edited to add the DSDT)

**Comment by SkyrilHD** [comment]
> The outside casing of the display itself is different from my stock 768p display. The original was a solid matte black, but this 1080p replacement has a subtle checkerboard pattern. Can anyone who has the e7250 with a stock 1080p touch display confirm whether that's normal or if mine may be from a different model?

I don't have the 1080p model, but looking at images, it seems like the checkerboard pattern is normal.

> All that being said, I'll drop an ioreg if anybody has the time to look at it; I've always been not quite sure what I'm looking for when I open IOregistryexplorer so any help is appreciated.

Thanks for the ioreg, looking at it, I don't see GPI0 loading. I think it needs some patches, which I thought was not needed as it was working before according to this thread: https://github.com/SkyrilHD/Dell-E7250-Hackintosh/issues/12

Also, on Windows, can you check if touch is connected via USB? The USBMap I provided was created on my 768p model. With this tool, you can check: https://github.com/USBToolBox/tool

**Comment by adyrosebrigg** [comment]
Okay, looking up the device in windows yielded a lot actually. Device manager says the digitizer's HWID is 03EB 8A83; Googling that lead me to a few results, one of which told me it's indeed an Atmel USB device and [one of which](https://macefi.com/sites/1311.html) was a hackintosh poster with an e5270. 

I thought that might have been a coincidental typo or regionally renamed variant of the same laptop, but searching e5270 shows it is an extant Dell laptop of similar--though not identical--build (I didn't look too deep into this but it seems to at least support 32gb max ram while afaik the e7250 supports only 16, so at least a different motherboard it seems).

That being said, if it is indeed an Atmel USB device, I can't say for sure much more about it. Here's what USBToolBox showed me:

![Screenshot 2022-05-28 173235](https://user-images.githubusercontent.com/615609/170845000-31e797f5-cbf2-4f18-bede-fa6e640b2407.png)

No idea what the two highlighted items are, but could it be one of those? And if so, should I try doing the full USBToolBox configuration and kext export and all?

**Comment by SkyrilHD** [comment]
If it's an Atmel touchscreen, I think you also need to add VoodooI2CAtmelMXT, which you can find in the VoodooI2C repo.

Googling shows that "5880" is the fingerprint scanner (which isn't supported), but I have no idea what "USB Composite Device" might be. I think it's probably the touchscreen, since you mentioned it showing up as "Atmel USB device".

My troubleshooting order would be:
1. Create a custom UTBMap kext WITH USB composite device (but mapped as USB 3 Type A) and try to use the touchscreen that way. (No VoodooI2C kext changes)
2. Add VoodooI2CAtmelMXT to the EFI (with UTBMap from the repo)
3. VoodooI2CAtmelMXT + your UTBMap

You can follow these instructions to build an UTBMap kext: https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/issues/28 or https://github.com/USBToolBox/tool#usage

If you need help, you can always message here.

**Comment by adyrosebrigg** [comment]
Okay, I gave those things a shot.

- UTBMap done, and loaded into the config. No change.
- I tried VoodooI2CAtmelMXT with both the repo's and my personal UTBMap. Nothing.
- Reflecting on GPI0 not appearing in my ioreg, I went back to dortania's guide and followed the steps to enable it [here](https://dortania.github.io/Getting-Started-With-ACPI/Laptops/trackpad-methods/manual.html). I now have GPI0 in ioreg, but the node has no children which I assume it probably should have if working.

<img width="852" alt="Screen Shot 2022-05-28 at 9 41 02 PM" src="https://user-images.githubusercontent.com/615609/170849737-2669408d-666f-4712-a719-87b5e0838220.png">

[updated ioreg](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/8792534/ady.s.e7250.ioreg.zip)

**Comment by SkyrilHD** [comment]
Checking your ioreg, I don't see the "USB Composite Device" loading at all.

![image](https://user-images.githubusercontent.com/28839925/170897242-6331fb1c-d8db-4d72-a70b-b270f0133f5c.png)

Also, I am surprised that I did not add XOSI to the config at all (which is an OS Check patch). I might add that with the next update. Can you try adding this SSDT to your EFI? [SSDT-XOSI.aml.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/8794609/SSDT-XOSI.aml.zip)
This should enable I2C0, which I don't currently see in your ioreg.

![image](https://user-images.githubusercontent.com/28839925/170898247-9e93b960-d161-467c-97e7-883e1da40ba7.png)

Checking your DSDT, the OSYS value must be greater than 0x07DC to enable I2C0 which corresponds to Windows 2013 (aka. Windows 8.1)

![image](https://user-images.githubusercontent.com/28839925/170898399-b33f6fee-e81b-4857-8ff6-97f64395919b.png)

![image](https://user-images.githubusercontent.com/28839925/170898429-d6686e42-2e04-43ae-849b-0970653ba3e0.png)

Do you mind sending your usb.json from the UTBMap, so I can merge it into my UTBMap?

**Comment by adyrosebrigg** [comment]
Here's my [usb.json](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/8805722/usb.json.zip).

As for enabling i2c0, I added the XOSI aml you shared and i2c0 still isn't showing up in [my current ioreg](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/8805764/ady.s.e7250.ioreg.zip).

Also, here's [a copy of my current ACPI folder](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/8805792/Ady.s.ACPI.folder.zip), in case it helps. This includes changes I made the other day per Dortania's guide as well as your XOSI from the previous comment.

Side note, and unrelated to the issue completely--I just discovered touch *does* work in the OpenCore loader itself, which was a bit of a surprise to me. I can use the touch display to tap the icon of an OS to boot it! Obviously unrelated to macOS actually loading/recognizing support for the hardware but neat nonetheless.

**Comment by SkyrilHD** [comment]
As for your ACPI folder, you do not need SSDT-OSYS as SSDT-XOSI does set the correct OSYS by itself.

![image](https://user-images.githubusercontent.com/28839925/171201122-44f0d535-0f34-43c5-a5c7-3344255a37be.png)

I find it odd that I can get GPI0 to work even without SSDT, so I'm guessing you don't need SSDT-GPI0 either?

Regarding usb.json, I see that you have mapped your webcam, bluetooth and touch as internal. At least, this results in a broken webcam and I changed it back to regular USB Type A. Let's see if the touch is recognized now.

[UTBMap 2.kext.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/8806216/UTBMap.2.kext.zip)

You can also try changing the ACSE value from One to 0x02 as this will be assigned to Windows 8.1.

![image](https://user-images.githubusercontent.com/28839925/171204143-8472f4f9-7545-4aaf-b07c-b81f83d06f2c.png)

**Comment by adyrosebrigg** [comment]
UTB imported. I didn't think to check webcam before rebooting, but it is working now. I'll keep an eye out for any usb issues in the future.

I removed OSYS and GPI0 from /ACPI/ (after making backups) and updated my config, but no change. GPI0 and I2C0 do not appear in [my current ioreg](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/8818374/ady.s.e7250.ioreg.v4.zip).
 
As for ACSE, what file should I modify that in? Or should I just copy what's in the above screenshot into a new file?

**Comment by SkyrilHD** [comment]
ACSE needs to be modified inside [SSDT-ACOS-ACSE.aml](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/blob/12.0/OpenCore/EFI/OC/ACPI/SSDT-ACOS-ACSE.aml) which is already included in the EFI.

Can you try the last version of VoodooI2C (2.6.5)? https://github.com/VoodooI2C/VoodooI2C/releases/tag/2.6.5

Also, according the VoodooI2C documentation Broadwell does not need GPI0 patches (?)

![image](https://user-images.githubusercontent.com/28839925/171509866-55a8bc3c-e64c-4893-af76-db306ade4a53.png)

VoodooI2C is sometimes so confusing...

**Comment by adyrosebrigg** [comment]
Ah, I overlooked that very file in the /ACPI/ dir. I updated the value to 0x02, no change.

Same for updating to the latest VoodooI2C. I replaced VoodooI2C, VoodooI2CAtmelMXT, and VoodooI2CHID with the latest released versions and no change there either.

This is all that appears in my ioreg tree when I search "Voodoo":

<img width="355" alt="Screen Shot 2022-06-01 at 5 18 33 PM" src="https://user-images.githubusercontent.com/615609/171511153-4d1fde15-1923-4391-8ab6-06457aa8f445.png">

**Comment by SkyrilHD** [comment]
I wonder if the USBToolBox kext is causing this issue because my WWAN is also not working anymore, IIRC it happened after I switched to USBToolBox...

Can you try the last version before I implemented USBToolBox? https://github.com/SkyrilHD/Dell-E7250-Hackintosh/tree/ae2faada709b5e2a5a4230f6395c32500b6c6130

![image](https://user-images.githubusercontent.com/28839925/171512611-af6c844d-85b5-4eca-8769-12751e8cc3ba.png)


Hopefully this will boot even though the EFI is months old, I recommend to put the EFI on a USB thumb drive (GPT, FAT32) for testing purposes.

**Comment by adyrosebrigg** [comment]
Oh my god, I can finally give you some good news: it worked!

I loaded up a spare usb drive with that EFI and checked ioreg:

<img width="355" alt="Screen Shot 2022-06-01 at 6 35 34 PM" src="https://user-images.githubusercontent.com/615609/171520412-fd7ad03b-ae6b-4a6b-a77a-7489c3d3a8ee.png">

Detected! So I added the latest Voodoo drivers to that, including AtmelMXT, rebooted, and:

<img width="316" alt="Screen Shot 2022-06-01 at 6 46 32 PM" src="https://user-images.githubusercontent.com/615609/171520507-03df6021-295f-4518-ae31-f4fadb537e43.png">

Touch working! In that EFI, at least.

So, what's next? I'm not sure if this is an issue with our UTB config, or if it's a bug in UTB itself. Thoughts?

**Comment by SkyrilHD** [comment]
Great! Let's see if USBToolBox is the issue: [USBMap.kext.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/8819528/USBMap.kext.zip)

Remove USBToolBox.kext and UTBMap.kext and add USBMap.kext to your EFI. This way we can avoid using USBToolBox but rely on native Apple classes. The only disadvantage is that it is paired to a single SMBIOS. Currently it is set to MacBook10,1.

**Comment by adyrosebrigg** [comment]
Okay, loaded that up & touch is working on my main EFI. Cool! So, confirmed working USB devices on my machine:

- Atmel Digitizer
- Internal Webcam
- Internal Bluetooth (on intel 7265)
- usb2 device plugged into each of the three external ports
- usb3 device plugged into each of the three external ports
  - I didn't test speeds but ioreg shows the device as a child of an XHCI device, so it seems it's correctly detected/routed.

So, I think we've done it! Is there anything else you'd like me to test? Or any files I can provide you from my end?

**Comment by SkyrilHD** [comment]
Perfect! I also need to add the USB port for WWAN, then I can add the USBMap to the repo. Thank you very much for testing and helping :)
