### ISSUE TITLE
HDMI does not work, monitor does not get detected on hackintosh

### ISSUE THREAD

**Issue by vaporisers** [SkyrilHD/Dell-E7250-Hackintosh#64]
Hello I am pretty new to hackintosh and got everything to work except dual monitors.

I am on macOS monterey with laptop HP 15-dw2xxx.

This is my current config file:
[config.plist.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/8822560/config.plist.zip)

Actually bluetooth and wifi at first also did not work but I fixed it using a wifi and bluetooth usb which now works fine.

My display settings window does not even show the display arrangement tab, just the tab for the main display to change scaling.

I tried to follow [this guide](https://www.tonymacx86.com/threads/guide-general-framebuffer-patching-guide-hdmi-black-screen-problem.269149/) but it was too complex for me and too time consuming.

Does anyone know a fix? Just comment if you need more information.

**Comment by SkyrilHD** [comment]
This is the wrong place to ask, as this repo aims for Dell Latitude E7250. You can get better help from forums.

Follow dortania's guide: https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/
