### ISSUE TITLE
Feature add: Booting Linux from OpenCore?

### ISSUE THREAD

**Issue by adyrosebrigg** [SkyrilHD/Dell-E7250-Hackintosh#65]
I'd like to propose an addition to your repo. By default, your EFI detects macOS and Windows installations/drives. Would you consider adding Linux support too, through `OpenLinuxBoot.efi` and `ext4_x64.efi`?

I've been using these in addition to your EFI and they work great (once I figured out that you actually *need* grub installed for OpenLinuxBoot to detect things). No config changes were needed; simply adding the two files to the `Drivers` directory and snapshotting in ProperTree made linux autodetection work in OpenCore & OpenCanopy.

Before I got into hackintoshing (this most recent time), my bootloader of choice was rEFInd, which I think is a common choice for people wanting a single graphical EFI boot manager that shows all of their OSes through smart autodetection. `OpenCore` + `OpenCanopy` + `OpenLinuxBoot` is a pretty solid drop-in replacement for that, while also supporting macOS, so I think supporting that configuration is a laudable goal.

That said, do you think this is a worthy addition to the repo? I don't want to push you to make it more bloated if that's your concern, but I think it would make a more well-rounded OOTB bootloader setup for people who want a drag-and-drop solution. I look forward to hearing your thoughts on the matter. Thanks for your work as always.

**Comment by SkyrilHD** [comment]
I agree, it is a worthy addition to the repo. I will add Linux support with the next update.
