### ISSUE TITLE
E7250’s lid sleep doesn’t work + on wake Bluetooth and trackpad crashes 

### ISSUE THREAD

**Issue by bravosixgoingdark** [SkyrilHD/Dell-E7250-Hackintosh#68]
So I tried troubleshooting according to the dortania guide and the sleep on this EFI is non functional and when it works Bluetooth crashed and the trackpad stopped working.

**Comment by SkyrilHD** [comment]
On Ventura, IntelBTPatcher causes issues with sleep. But broken trackpad was fixed a long time ago. What OS are you using? Is anything plugged in to the laptop when you put it to sleep? Which EFI version are you using?

**Comment by bravosixgoingdark** [comment]
First, I run Monetery since Ventura have issues (notably with WiFI). I'm using the 12.0 branch of the EFI and I need to plugin my laptop to properly sleep otherwise it would just reboot when I turn it on without a charger. Another issue for me is the fact that AppleID keeps signing out after a reboot (even with SMBIOS changed a couple of time, I guess Apple is fucking with me somehow).

**Comment by bravosixgoingdark** [comment]
Note: waking up from lid sleep crashes the whole thing

**Comment by SkyrilHD** [comment]
For me, this only happens on Ventura. Monterey works for me without any issue. Maybe try updating to the latest EFI release. There are updates for Monterey as well.

About Apple ID, I highly suggest reading this [guide](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html).

**Comment by bravosixgoingdark** [comment]
So disabling IntelBTpatcher kinda fixed the issue with Bluetooth tho and also changing my SMBios to MacBookAir7,2 did fix the AppleID issues. Sleep kinda works right now with a charger but crashes on battery. So maybe it's safe to close this issue for now.

**Comment by bravosixgoingdark** [comment]
(edit sleep is kinda fixed too) thanks a lot for the hint over IntelBTPatcher tho

**Comment by bravosixgoingdark** [comment]
Thanks for the help!
