### ISSUE TITLE
HDMI: Not Working On Ventura

### ISSUE THREAD

**Issue by devsurajrai** [SkyrilHD/Dell-E7250-Hackintosh#69]
I upgraded to Ventura via OTA. Found out that HDMI is not working. Haven't patched GPU acceleration yet. Please guide.

**Comment by SkyrilHD** [comment]
Everything is written in the README. Check here: https://github.com/SkyrilHD/Dell-E7250-Hackintosh#gpu-acceleration-on-ventura
