### ISSUE TITLE
How to fix Wi-fi connection in Intel Wifi Card

### ISSUE THREAD

**Issue by reberthkss** [SkyrilHD/Dell-E7250-Hackintosh#7]
Hi @SkyrilHD 
I'm pretty close to finish hackintosh on my latitude, i just need know how i can will do the fix on Wi-fi connection in Intel Wifi Card.

thanks in advance!!

**Comment by SkyrilHD** [comment]
Hi,

I got it working with this project:
zxystd/itlwm (google it)

These are the steps:
1. install Xcode
2. open Terminal and type `git clone https://github.com/zxystd/itlwm.git`
3. open the project
4. In Xcode, go to `itlwm/mac80211.cp` and Command+F for `*ssid_name`. (It should be at line 1997 and 1998) and replace the SSID and password with yours
5. Then go to `fw_gen.sh` and remove line 11 `if [!-f target_file]; then` and line 40 `fi`
7. Select fwgen as target and build
6. In project settings, go to build settings then in itl80211, change the "Development Team" to Other and leave it empty
9. Choose target as itlwm and build
10. In the project explorer go to products and right-click on itlwm.kext and reveal in finder
11. In Terminal, give itlwm.kext its permissions (chmod -Rf 755 and chown -Rf 0:0)
12. To test it use kextload, and verify in System Preferences that Wi-Fi is connected (it will show as Ethernet)
13. Enjoy!

**Comment by Lusanta25** [comment]
sorry @SkyrilHD  but when at the third step you say: open the project ... how can I do it ? 
Thx in advance, I'm quite a noob on the matter.
Cheers, Luca.

**Comment by SkyrilHD** [comment]
Open your home folder in finder (Shift + Command (Windows-Key) + H) then there should be a folder called itlwm. Open the folder and open the project called: itlwm.xcodeproj

**Comment by Lusanta25** [comment]
thanks for the answer, I have done another few passages but I'm already stuck because of noobness in using Xcode =( 
![Schermata 2020-05-16 alle 18 29 39](https://user-images.githubusercontent.com/60262306/82125043-75339680-97a3-11ea-8874-29671c253238.png)
So my question this time is: what shall I remove from the line 11 ? (I've attached a photo so that you can see) and I've also another doubt when you say build (example: choose target as itlwn and build) what do you mean by using the verb build ? 
Thanks in advance man for the reply, I hope you a good evening. 
Cheers, Luca.

**Comment by SkyrilHD** [comment]
zxystd removed the line in his latest commit... (skip step 5)

Select as shown in this picture:

![image](https://user-images.githubusercontent.com/28839925/82126318-3f46e000-97ac-11ea-83d5-a897071a8103.png)
 
Then press the "Play" button on the left side. After it says "Build successful". You should see this file:

![image](https://user-images.githubusercontent.com/28839925/82126396-c6945380-97ac-11ea-917d-7f7cf94bc8de.png)

Then continue from step 7.

**Comment by Lusanta25** [comment]
thx mate for the reply, I've done the things you said me and I've succeeded in doing the sixth passage but still don't managed to get the seventh done right. I'm still struggling to understand where I need to select the Development Team ? (I will attach a picture in order to understand better). 
![Schermata 2020-05-16 alle 20 56 25](https://user-images.githubusercontent.com/60262306/82127993-b9c92d00-97b7-11ea-9a18-7b7c0c5c0131.png)
Thanks in advance for the attention, I hope you a good evening. 
Cheers, Luca.

**Comment by SkyrilHD** [comment]
I hope this helps

![image](https://user-images.githubusercontent.com/28839925/82128188-84254380-97b9-11ea-82af-49a001219a74.png)

**Comment by Lusanta25** [comment]
thx a lot mate, now I'm stacked at the last passage, how I can kext load the itlwm.kext ? 
Thx in advance for the reply, cheers. 
Luca

**Comment by SkyrilHD** [comment]
Type this in Terminal: `sudo kextload ` then drag the kext into Terminal and press enter

**Comment by Lusanta25** [comment]
![Schermata 2020-05-17 alle 11 26 35](https://user-images.githubusercontent.com/60262306/82140759-52e85a00-9831-11ea-864e-001814f9d035.png)
man it gives me this error =( 
Any ideas on how to fix it?

**Comment by SkyrilHD** [comment]
did you give permissions?

**Comment by SkyrilHD** [comment]
`sudo chown -Rf 0:0 ` *drag the file into Terminal*
`sudo chmod -Rf 755 ` *drag the file into Terminal*

**Comment by Lusanta25** [comment]
okay now I've done it but in system preferences says a lot of ethernet, but noone seems to work, shall I restart the OSX? 
![Schermata 2020-05-17 alle 12 37 25](https://user-images.githubusercontent.com/60262306/82142274-5ed91980-983b-11ea-829c-572af1d9da84.png)
![Schermata 2020-05-17 alle 12 37 45](https://user-images.githubusercontent.com/60262306/82142275-60a2dd00-983b-11ea-9e7a-d14cb6d423f0.png)

**Comment by SkyrilHD** [comment]
Hmmm it should usually show up on its own

**Comment by SkyrilHD** [comment]
Make sure that you have entered your SSID and password correctly

**Comment by Lusanta25** [comment]
I'm quite sure that I have written the right SSID and password in Xcode but I'll check in the next few hours and keep you up on the matter.
Cheers, Luca.

**Comment by Lusanta25** [comment]
men I've redone everything and now it works, so thankful to you =) 
Do you think that also airdrop now should work ? @SkyrilHD 
Cheers and another time thanks, Luca.

**Comment by SkyrilHD** [comment]
Sadly, Airdrop doesn't work. We have to be patient. It's important to have stability first, so new "features" can be added with no problems.

**Comment by Lusanta25** [comment]
Hi @SkyrilHD do we have any news about the possibility to get airdrop working on this machine?

**Comment by SkyrilHD** [comment]
Currently, there is no AirDrop implementation but Universal Clipboard and such are getting supported...

The AirDrop window is there but as I said before it doesn't work...

![IMG_20200928_154254_786](https://user-images.githubusercontent.com/28839925/94439988-63c2b800-01a1-11eb-8c0a-300c0f5638da.jpg)
