### ISSUE TITLE
E7250 Installer does't work

### ISSUE THREAD

**Issue by Marc90F** [SkyrilHD/Dell-E7250-Hackintosh#71]

**Comment by Marc90F** [comment]
I Format my USB Drive (8GB) in FAT32 GPT from Rufus, then i copy com.apple.recovery.boot, and the EFI (downloaded by https://github.com/SkyrilHD/Dell-E7250-Hackintosh/releases/), after i Boot in the usb, and in the OpenCore Boot Interface there isnt no Mac os installer (i use macrecovery.py by dortania's guide, HELP ME, i'm italian

Im trying to instal ventura

**Comment by Marc90F** [comment]
![Immagine 2023-09-05 140451](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/assets/144126291/26e24e59-c8ab-41bb-9f7f-97a85b06e26d)

**Comment by Marc90F** [comment]
Inside of com.apple.recovery.boot folder (i use macrecovery.py)
![Immagine 2023-09-05 140608](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/assets/144126291/574bab32-fae8-4a4c-9bac-717d93b1f046)

**Comment by SkyrilHD** [comment]
Try pressing space bar in the OpenCore menu

**Comment by Marc90F** [comment]
Ok, it works! Thanks a lot!
