### ISSUE TITLE
Problem with MacOs Installer

### ISSUE THREAD

**Issue by Marc90F** [SkyrilHD/Dell-E7250-Hackintosh#72]
What my Ventura is only installablr with Ethernet? Can you plis tell me why? I want Install with WiFi

**Comment by SkyrilHD** [comment]
Read the README

https://github.com/SkyrilHD/Dell-E7250-Hackintosh#intel-wifi

**Comment by Marc90F** [comment]
Bro how can activate Intel WiFi?

**Comment by Marc90F** [comment]
Brooo help meeeee

**Comment by SkyrilHD** [comment]
https://github.com/SkyrilHD/Dell-E7250-Hackintosh/issues/38#issuecomment-938086417
