### ISSUE TITLE
Somebody can give me a perfect config.plist with EVERYTHING, Intel WiFi, Bluetooth activated, im from ventura, i have no touchscreen version

### ISSUE THREAD

**Issue by Marc90F** [SkyrilHD/Dell-E7250-Hackintosh#73]

**Comment by Marc90F** [comment]
Help me, I know I'm not very very very good, but can somebody give me config.plist for Ventura, no toudchscteen version m, thanks

**Comment by SkyrilHD** [comment]
First, learn how to read a README before opening issues (some might call it RTFM). After reading, you will understand it will take you 30–40 seconds to create a 'perfect config.plist'. If you do not know how to edit plist files, please quit hackintoshing and go back to Linux or Windows. Also, learn to be patient and use your time to read a few sentences. You will go far.
