### ISSUE TITLE
Wireless problem

### ISSUE THREAD

**Issue by Marc90F** [SkyrilHD/Dell-E7250-Hackintosh#75]
I Install Mac OS monterey in my e7250, with Ethernet and then i activated airport ,btpatcher, bluetoolfixup and intellbluetooth firmware in the config.plist, then i copy the efi in my hardrive (monterey installed) after I boot the wireless card doesnt start, why i think THAT? Because there is wireless light under the display, near the keybord in the right top, and is not illuminated, everything is perfect. Now you are thinking the wireless card is broken, no,i installed Windows 10 in another SSD e work oerfectly, help me

**Comment by Marc90F** [comment]
Help me you are the onwer of this repo

**Comment by nunnethan** [comment]
You seem to think that @SkyrilHD (or anyone else who is interested in this repo) is obliged to help you. They're not. If you'd like to ask nicely for help, manners cost nothing. But feeling entitled to help when you haven't paid a penny for something is dick behaviour. 

You might want to check to see if you're still accidentally booting from the USB drive.
