### ISSUE TITLE
Authorization App Help

### ISSUE THREAD

**Issue by Marc90F** [SkyrilHD/Dell-E7250-Hackintosh#77]
After freaking out to install sonoma on my e7250 i have a little problem, THE AUTHORIZATION! Every app send the request of cam, mic, ecc. i go to privacy setting, there is a label says: here are the apps who send a request, but, there is no app. Everything works, i wanna thank you and your community for creating this repo, i very appreciate bro.

**Comment by Marc90F** [comment]
Like I said this is a great project

**Comment by SkyrilHD** [comment]
Can you tell which apps do not show up, so I can test it for myself

**Comment by Marc90F** [comment]
every app

**Comment by Marc90F** [comment]
I serched ongoogle, i find this guy: https://www.youtube.com/watch?v=NZNW62-DfIE&t=93s&ab_channel=Jessie%27sFlying
It's a shoot yourself in the balls, every time, anyways, this method doesn't work every time, example. When i try to patch com.native-instruments.Guitar Rig 6 (id app of Guitar Rig 6) the program doesn't work, becouse the name of id is SO LONG (it understood com.native-instruments.Guitar)

**Comment by Marc90F** [comment]
i don't use translator because im' stupid. im italian

**Comment by Marc90F** [comment]
here is the link due the guy linked on his youtube. https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#unable-to-grant-special-permissions-to-apps-ie-camera-access-to-zoom
