### ISSUE TITLE
Fan Always high

### ISSUE THREAD

**Issue by ran2k** [SkyrilHD/Dell-E7250-Hackintosh#79]
Hey,
how can I fix it my fans are always at high 5000 rpm on sonoma

**Comment by SkyrilHD** [comment]
I don't see how this is an issue with the EFI. You could do several things:

- Check for CPU usage:
    - if the CPU usage is high, check if you installed the latest version of OCLP (since there were many bug fixes for our Broadwell graphics kext)
        - if the CPU is still high, check which process uses the most CPU

    - if the CPU usage is low, check for the temperature of the CPU
        - if the temperature is high, it's time for a new thermal paste (It has been 9 years since the laptop has been released, so a reapply of thermal paste is helpful)
            - also clean the inside of the laptop
        - if the temperature is low, there might be some issues with the motherboard or how the board talks to the fan
            - either the fan is giving up, or you could try a BIOS and NVRAM reset
