### ISSUE TITLE
Airportitlwm causes shut off

### ISSUE THREAD

**Issue by Promethilaus** [SkyrilHD/Dell-E7250-Hackintosh#81]
Hiya thanks for the config I am admittedly a noob at hackintoshing but I managed to get everything working except Bluetooth and wifi I tried using OpenCore Configurator and manually changing the config.plist file to enable the 4 files lead to shut off I can get as far as at best the Mac OS desktop before it shuts off do you have any idea on how to fix?

Thanks in advance for any provided aid

**Comment by SkyrilHD** [comment]
Which macOS version are you using?

**Comment by Promethilaus** [comment]
Sonoma

**Comment by SkyrilHD** [comment]
Try updating the kext: https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.3.0

**Comment by Promethilaus** [comment]
Fixed thanks very much before I close the issue any idea on how to get built in SD card reader to work?

**Comment by SkyrilHD** [comment]
The SD-card reader should be enabled by default. However, it has some issues reading some types of cards. I cannot fix this issue, as we are using Apple's SD card driver.

**Comment by Promethilaus** [comment]
Fair enough I think the reason I couldn't boot with that version of airportitlwm is because it was designed for Mac OS 14.0 - 14.3 and something gets changed in 14.4 onwards requiring a different version

**Comment by SkyrilHD** [comment]
Yes, I need to update this repo at some point. Couldn't find any time to do it. Might do it tomorrow before/after WWDC.
