### ISSUE TITLE
patiently waiting for sequoia

### ISSUE THREAD

**Issue by m6el** [SkyrilHD/Dell-E7250-Hackintosh#83]
release sequoia fr 😊

**Comment by SkyrilHD** [comment]
deadass fr fr

![Screenshot 2024-08-22 at 14 06 05](https://github.com/user-attachments/assets/6cea2a97-8b19-4992-a473-ab878d642022)

<img width="311" alt="image" src="https://github.com/user-attachments/assets/8899c552-2d2f-4704-a4a9-40de26f0996c">


The early preview of OCLP works very well. Will probably release the latest version of OpenCore for Ventura next month (which will be the last). Then I will release the Sonoma EFI right after.

**Comment by m6el** [comment]
woahh no way, might try download, lowkey appreciate your work saves so much time

**Comment by m6el** [comment]
What changes did you do to get Sequoia running?

**Comment by SkyrilHD** [comment]
Just downloaded the Ventura EFI and added `-lilubetaall`. You also need to update VoodooPS2Controller to make the trackpad work again. For the GPU acceleration, download the latest nightly OCLP from the pull request of the OCLP repo. I think that should be it.

**Comment by m6el** [comment]
Thanks, I'll try now also where did you get the sequoia disk installer from? (feel free to close this issue after this)

**Comment by SkyrilHD** [comment]
I got it from another supported Mac. I created the installer with createinstallmedia. I am not sure if it is allowed to share the link, but you need the InstallAssistant.pkg. Check for `062-64510` on Google.

I will keep the issue open for visibility, however for each major update I usually create a discussion to keep the issues page clean. https://github.com/SkyrilHD/Dell-E7250-Hackintosh/discussions/82

**Comment by SkyrilHD** [comment]
A new version of the EFI has been released: https://github.com/SkyrilHD/Dell-E7250-Hackintosh/releases/tag/v6.0
