### ISSUE TITLE
hdmi does not work

### ISSUE THREAD

**Issue by ghost** [SkyrilHD/Dell-E7250-Hackintosh#9]
Hi,
I have installed successfully macOS Catalina and it's working fine, but I have found that hdmi doesen't work because when i plug in an external monitor i have a black screen on the laptop monitor and the external doesen't found ani signal. To restore the laptop I have to reboot it because if I unplug the hdmi it still has a black screen. Any fix?

**Comment by SkyrilHD** [comment]
very weird... I used my laptop on HDMI 2 days ago. Which EFI do you use?

- Can you check if TV/Mointor is set to the right input...
- make sure the cable isn't broken or something
- check if the HDMI port has no bent pins

**Comment by ghost** [comment]
I am using OpenCore EFI.
I have tried with two different monitors and two different cables but with windows it works fine so I think it's a macOS issue.

**Comment by SkyrilHD** [comment]
Can you shutdown the laptop and plug the hdmi cable in and boot into macOS?

**Comment by ghost** [comment]
I got black screen one second after apple logo glitches

**Comment by SkyrilHD** [comment]
Can you put light on the display to see if only the backlight is off?

Logs would help but I don't know how to get it

**Comment by ghost** [comment]
I think it's a crash because caps light doesen't work. 
This is my ioreg
https://drive.google.com/file/d/1-K4gVWXxNyT49haRUjhlZnhwo0XONkRh/view?usp=sharing

**Comment by SkyrilHD** [comment]
soooo, I compared the ioreg with mine and found this:

![image](https://user-images.githubusercontent.com/28839925/94351049-e68a2c80-0054-11eb-95ef-aaf0e0b980b7.png)

your agpm doesn't show up and there is some Framebuffer missing

which version of macOS are you using?
what is your iGPU (HD 5500?)
can I see a screenshot of Monitor in system preferences and about this Mac

**Comment by ghost** [comment]
I'm using 10.15.6 (19G73) with HD5500
![Schermata 2020-09-27 alle 00 11 51](https://user-images.githubusercontent.com/22156852/94351143-200f6780-0056-11eb-8fea-91c99abf661f.png)
![Schermata 2020-09-27 alle 00 11 31](https://user-images.githubusercontent.com/22156852/94351145-20a7fe00-0056-11eb-9d38-59941098eb76.png)

**Comment by SkyrilHD** [comment]
ouu you are using the FHD version... I am using 1366x768

also i am using macOS 10.15.4, I will update my laptop when I have some free disk space to confirm this. (which is my guess, macOS 10.5.6 maybe broke something)

but I will keep this issue open until I find something which fixes it

**Comment by ghost** [comment]
Ok, thanks

**Comment by SkyrilHD** [comment]
Hi

can you replace the current config with this one and try out again?
I changed the Framebuffer with the recommended one which can be found in the WhateverGreen Documentations.

[config.plist.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/5288319/config.plist.zip)

**Comment by ghost** [comment]
I'm trying but the laptop is going on stop randomly

**Comment by ghost** [comment]
The external monitor is now working, thank you!

**Comment by SopAme1996** [comment]
hello good evening, sorry for the trouble I have the same problem. my computer is a laptop i5 7200u + nvida 940mx almost everything works fine, what is failing is the hdmi. When I connect the hdmi the computer restarts. i am using macOS catalina. I would appreciate your help

**Comment by SkyrilHD** [comment]
Wrong place to ask, as this is only related to 5th gen CPU. Make sure you set your platform-id correctly and if it is I recommend checking out how to do a connector patch.
Also maybe your HDMI is connected to the NVIDIA GPU which is not supported as therefore causes the system to crash.

Ask on forums instead of here, if you want more help.
